### ISSUE TITLE
DHCP/PXE zarf package

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf-package-bare-metal#1]
We need to explore running a DHCP/PXE server from a Zarf package (ideally using `k3s` from zarf init as a simple utility cluster).  This would include the following:

1. Running a DHCP/PXE server to provide offers on the local LAN
2. Wiring up services (probably NodePort?) to expose the services to the LAN
3. Packaging everything with Zarf so that it is self-contained and portable

**Comment by docandrew** [comment]
Possibly useful: https://github.com/kubefarm/dnsmasq-controller

I've had success in the past using dnsmasq to provide PXE boot where other DHCP/PXE servers didn't work.

**Comment by Racer159** [comment]
Other relevant links from @wirewc

https://cobbler.readthedocs.io/en/latest/quickstart-guide.html
https://medium.com/@Iqbalkhattra85/pxe-boot-installing-os-like-a-pro-af0582756128

**Comment by docandrew** [comment]
Potential stretch objective: https://github.com/ipmitool (for powering on machines using BMC, managing boot order, etc. to do a 100% hands-off cluster rebuild)

**Comment by wirewc** [comment]
Context behind the links @Racer159 mentioned. 

* Cobbler is the ideal tool to use in conjunction of The Foremen/Red Hat Satellite for provisioning. 
* Coordination and setup with the certs needed for 802.3u specifications do need to be considered when working in a highly regulated environment. 
* TFTP is used for the initial image pull
* Traditionally for in place installs, the port is set to a different VLAN with DHCP specific for only doing builds. Once the builds are complete, the network engineer will flip the port back to the regular network. 
   * This is done because some the initial setup may not be as restricted. 
   * Security is enforced by sandboxing the network and through control from the network engineer only. 
* If not provisioning hardware and only using PXE, note that PXE + Puppet is the preferred pattern for HPC and other highly regulated environments that need to enforce consistency quickly while remaining fairly stateless.

**Comment by btlghrants** [comment]
Lots of interesting stuff on this list:  https://github.com/alexellis/awesome-baremetal/blob/master/README.md#self-hosted
